from loguru import logger

DB_PATH = "../volume/db/project.db"

EXPERIMENT_INIT = (
    "DROP TABLE IF EXISTS {TABLE_QUERIES}; "
    "DROP TABLE IF EXISTS {TABLE_QRELS}; "
    ""
    "CREATE TABLE {TABLE_QUERIES} (ID NUMBER PRIMARY KEY, QUERY_ID NUMBER, DATA TEXT); "
    "CREATE TABLE {TABLE_QRELS} (ID NUMBER PRIMARY KEY, QUERY_ID NUMBER, DOC_ID NUMBER); "
    "CREATE UNIQUE INDEX {TABLE_QUERIES}_1_ID ON {TABLE_QUERIES}(QUERY_ID); "
    "CREATE INDEX {TABLE_QRELS}_1_ID ON {TABLE_QRELS}(QUERY_ID); "
    "CREATE INDEX {TABLE_QRELS}_2_ID ON {TABLE_QRELS}(DOC_ID); "
    ""
    "DROP VIEW IF EXISTS {JOINED_VIEW}; "
    "CREATE VIEW {JOINED_VIEW} AS "
    "SELECT QR.ID ID, Q.QUERY_ID, Q.DATA QUERY_DATA, D.DOC_ID, D.DATA DOC_DATA FROM {TABLE_QRELS} QR "
    "LEFT JOIN DOCS D ON QR.DOC_ID = D.DOC_ID "
    "LEFT JOIN {TABLE_QUERIES} Q ON QR.QUERY_ID = Q.QUERY_ID;"
)

LOG_PATH = "pipeline.log"
logger.add(LOG_PATH, colorize=True,
           format="{time:YYYY-MM-DD at HH:mm:ss} {function: <20} {level: <8} {message}", level="DEBUG")
